"""Symmetric e-prop feedback weights B_jk (Bellec et al. 2020, Eq. 4/37).

The learning signal L_j^t is generated by routing output errors to the LSNN
neurons through feedback weights B_jk:

    L_j^t = Σ_k B^π_jk · (π_k^t − 1_{a=k}) + c_V · B^V_j                  (Eq. 37)

The value term c_V · B^V_j is a CONSTANT (no error factor): it only tells
neuron j how much it influences the value prediction. The value ERROR is
carried by the global reward prediction error δ_t in the plasticity rule
(Eq. 36), not inside L_j. The `critic_error` argument here is the constant
multiplier on B^V (always 1.0 from agent.py); it is NOT (V_{t+1} − V).

SEAL uses **symmetric e-prop** with **separate actor and critic feedback
channels**, matching the paper's Eq. 37 notation where B^π and B^V are distinct:

    B^π_jk = (Wout^π_kj)^T        (transpose of the actor readout weights)
    B^V_j  = (Wout^V_j)^T         (transpose of the critic readout weight)

B is NOT a separate parameter. It is a **live view** of the readout weights'
transposes, read at the moment L_j is computed, so it always tracks the current
readout weights with zero staleness. No plasticity rule acts on B itself.

This is the variant the paper used for the Atari Pong result (Fig. 4b/d,
"reward-based symmetric e-prop"). It gives the strongest, lowest-noise learning
signal because L_j then equals the exact partial derivative ∂E/∂z_j. The cost
is "weight transport" (B_jk must know Wout_kj), which is biologically implausible
but maximizes sample efficiency. Separating actor/critic feedback (rather than
sharing one matrix) ensures the critic's value error gets its own undiluted
channel into the LSNN, so V can actually learn — matching the paper's structure.
"""
from __future__ import annotations
import torch
import torch.nn as nn


class FeedbackWeights(nn.Module):
    """Symmetric e-prop feedback: B^π = (Wout_actor)^T, B^V = (Wout_critic)^T.

    Live views (no parameters). Shape: both map output errors -> L_j [n_total].

    Args:
        n_total: number of LSNN neurons j
        n_actor: number of action outputs
        n_critic: 1
        readout: the LeakyReadout module whose Wout_actor / Wout_critic are
                 transposed to form B^π / B^V. Held by reference; read live.
    """
    def __init__(self, n_total: int, n_actor: int, n_critic: int = 1,
                 readout: nn.Module = None):
        super().__init__()
        self.n_total = n_total
        self.n_actor = n_actor
        self.n_critic = n_critic
        self.n_out = n_actor + n_critic
        if readout is None:
            raise ValueError("Symmetric e-prop requires the readout module "
                             "to read Wout_actor/Wout_critic (B = Wout^T).")
        self.readout = readout

    @property
    def B_pi(self) -> torch.Tensor:
        """Live view: B^π_jk = (Wout_actor_kj)^T, shape [n_total, n_actor]."""
        return self.readout.Wout_actor.t()

    @property
    def B_v(self) -> torch.Tensor:
        """Live view: B^V_j = (Wout_critic_j)^T, shape [n_total, n_critic]."""
        return self.readout.Wout_critic.t()

    def learning_signal(self, policy_error: torch.Tensor,
                        critic_error: float,
                        c_v: float) -> torch.Tensor:
        """Compute L_j^t = B^π·policy_err + c_V·B^V·critic_const  (Eq. 37).

        `critic_error` is the constant multiplier on B^V (1.0 from agent.py):
        the value term of L_j is the constant c_V·B^V_j. The value ERROR is
        gated by δ_t in eprop_opt.step(delta) (Eq. 36), NOT passed in here.

        Runs under torch.no_grad() — L_j is used in the manual e-prop tag
        accumulation, NOT in autograd. Without this, B (= Wout^T, a Parameter
        view) would make L_j carry a grad_fn that leaks into the tags.
        """
        with torch.no_grad():
            L = self.B_pi @ policy_error                      # [n_total]
            critic_vec = torch.full((self.n_critic,), float(critic_error))
            L = L + c_v * (self.B_v @ critic_vec)            # [n_total]
            return L

    def drift_from_init(self, B_init: torch.Tensor = None) -> float:
        """No-op diagnostic. Symmetric B tracks Wout^T; there is no separate
        B to drift. Returns 0.0 so existing logging/columns stay valid."""
        return 0.0
